runtime: nodejs12

instance_class: F4
automatic_scaling:
  max_concurrent_requests: 100

handlers:
- url: /static
  static_dir: public/static
  secure: always

- url: /images
  static_dir: public/images
  secure: always

- url: /legal$
  static_files: public/legal/index.html
  upload: public/legal/index.html
  secure: always

- url: /legal/cookies$
  static_files: public/legal/cookies/index.html
  upload: public/legal/cookies/index.html
  secure: always

- url: /privacy$
  static_files: public/privacy/index.html
  upload: public/privacy/index.html
  secure: always

- url: /$
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /favicon.ico$
  static_files: public/favicon.ico
  upload: public/favicon.ico
  secure: always

- url: /robots.txt$
  static_files: public/robots.txt
  upload: public/robots.txt
  secure: always

- url: /ads.txt$
  static_files: public/ads.txt
  upload: public/ads.txt
  secure: always

- url: /favicon.ico.png$
  static_files: public/favicon.ico.png
  upload: public/favicon.ico.png
  secure: always

- url: /manifest.json$
  static_files: public/manifest.json
  upload: public/manifest.json
  secure: always

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
