runtime: nodejs12

handlers:
- url: /static
  static_dir: public/static
  secure: always

- url: /images
  static_dir: public/images
  secure: always

- url: /legal
  static_dir: public/legal
  secure: always

- url: /privacy
  static_dir: public/privacy
  secure: always

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
