[workspace]

members = [
    "src/engine-v2",
    "src/importer",
    "src/mdl",
    "src/system-dynamics-compat",
    "src/system-dynamics-engine",
    "src/xmutil",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = 3
lto = false
debug = 1
