[workspace]

members = [
    "src/engine",
    "src/importer",
    "src/mdl",
    "src/system-dynamics-compat",
    "src/system-dynamics-engine",
    "src/xmutil",
]

[profile.release]
opt-level = 3
lto = false
debug = 1
panic = "abort"
