[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2018-0015",
    "RUSTSEC-2020-0053",
]

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "CC0-1.0",
    "MIT",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.9

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[[bans.skip]]
name = "cfg-if"
version = "=0.1"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
    "https://github.com/danburkert/prost",
]
