[package]
name = "simlin-engine"
version = "0.1.0"
authors = ["Bobby Powers <bobbypowers@gmail.com>"]
license = "Apache-2.0"
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["rlib"]

[features]
wasm = ["wasm-bindgen"]

[dependencies]
lazy_static = "1"
regex = "1"
unicode-xid = "0.2"
lalrpop-util = { git = "https://github.com/bpowers/lalrpop", version = "0.19.5", rev = "2b45b46ca26fc1700cd1319a02b7e7b1dc457412" }
prost = { git = "https://github.com/bpowers/prost", version = "0.7", rev = "d688bc4b89fcdfe26abb22869eac0f3d3770f17d" }
float-cmp = "0.8"
ordered-float = "2"
smallvec = { version = "1", features = [ "union" ] }
wasm-bindgen = { version = "0.2", optional = true }

[dev-dependencies]
rand = "0.8"

[build-dependencies]
lalrpop = { git = "https://github.com/bpowers/lalrpop", version = "0.19.5", rev = "2b45b46ca26fc1700cd1319a02b7e7b1dc457412" }
prost-build = { git = "https://github.com/bpowers/prost", version = "0.7", rev = "d688bc4b89fcdfe26abb22869eac0f3d3770f17d" }
