[package]
name = "mdl"
version = "0.1.0"
authors = ["Bobby Powers <bobbypowers@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
clap = "2"
stringreader = "0.1"
system-dynamics-engine = { version = "0.1", path = "../system-dynamics-engine" }
xmutil = "1.1"
